stages:
  preprocess:
    cmd: python src/data_processed.py
    deps:
      - src/data_processed.py
      - data/raw/house_data.csv
      - params.yml
    outs:
      - data/processed/processed_data.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/processed_data.csv
      - params.yml
    outs:
      - model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/processed/processed_data.csv
      - params.yml
      - model.pkl
    metrics:
      - scores.json
