data_path: data/raw/house_data.csv
processed_data_path: data/processed/processed_data.csv

train:
  test_size: 0.4
  random_state: 42

model_params:
  n_estimators: 100
  max_depth: 10
  random_state: 42